networks:
  sparkpg_network:

services:
  spark-master:
    image: my_first_spark
    build: .
    container_name: spark-master
    networks:
      - sparkpg_network
    entrypoint: /bin/bash
    command: -c "/opt/spark/sbin/start-master.sh; tail -f /dev/null"
    ports:
      - '8080:8080'
      - '4040:4040'
    volumes:
      - .:/app
      - spark-events:/opt/spark/events

  spark-worker:
    image: my_first_spark
    build: .
    container_name: spark-worker1
    networks:
      - sparkpg_network
    entrypoint: /bin/bash
    command: -c "/opt/spark/sbin/start-worker.sh  spark://spark-master:7077; tail -f /dev/null"
    volumes:
      - spark-events:/opt/spark/events  
    
  spark-history-server:
    image: my_first_spark
    build: .
    container_name: spark-history-server
    networks:
      - sparkpg_network
    entrypoint: /bin/bash
    command: -c "/opt/spark/sbin/start-history-server.sh; tail -f /dev/null"
    volumes:
      - spark-events:/opt/spark/events 
    ports:
      - '18080:18080'

  # Postgresql database instance
  postgres:
    image: postgres:13
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sparkpg_network
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  # Website that can be used to connect, administrate and develop postgresql databases
  pgadmin:
    image: dpage/pgadmin4
    networks:
      - sparkpg_network
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8050:80"

volumes:
  spark-events: